### ISSUE TITLE
Encryption error

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-iOS#179] opened 2016-08-23 03:56 UTC
Getting encryption errors in msgs.

**Comment by n8fr8** [comment] 2016-08-23 13:10
We need more details than this in the future please. Screenshots, specifics of what the messages contents, are, etc. I am attaching a screenshot I have of the issue. 

Specifically seeing this: "<error type="cancel"><service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"></error>

![file_000](https://cloud.githubusercontent.com/assets/30851/17892858/5469d7da-6911-11e6-96f5-d4a81b988f2b.png)

**Comment by chrisballinger** [comment] 2016-08-23 18:09
This is a message indicating that the server is down, which we previously
ignored, not an encryption error. I believe there is another message
indicating when the other client is offline, because Dukgo doesn't queue
offline messages. If messages are sent while the server is down they will
disappear into the ether, until we merge our message queue. I was trying to
tweak the error handling code to better handle some edge cases related to
Conversations, and in the process made it overly verbose. This code is
still in development and perhaps should have been in another branch, but
the develop branch can still potentially be unstable at times and generally
needs some regression testing before moving to production.

We could revert to suppressing the errors, but perhaps there is some better
UX we could use to indicate failure states without spamming the user with
too many identical errors. There are also some general server errors that
we still ignore, like Calyx's warning that OTR is required.

Tracking upstream issue here:
https://github.com/ChatSecure/ChatSecure-iOS/issues/554

**Closed** 2016-11-28 22:14 UTC
Labels: high-priority
