### ISSUE TITLE
New admin permissions missing

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#573] opened 2018-03-29 17:56 UTC
If you are in a group and are made a new admin (given permission from the group creator) some permissions are missing. 

In and working:
-crown (shown in all members' rosters)
-change group name
-add friends

Missing and not working:
-tapping on members name in the roster only shows "view profile"
Not shown: "make admin" and "kick out" 

-**Bug**: When the iPad became a new admin and tapped on any profile in the group roster the app crashed, every time. 

Device: iPhone 7
OS: 11.2.2

Device: iPhone 6
OS: 10.3.3

Device: iPad
OS: 10.3.2

App version: 126

**Comment by N-Pex** [comment] 2018-04-05 13:05
@tiffrobo The ipad crash I'll have a look at.

The other is not a bug - the new person is an ADMIN, not an OWNER, so can't do kick and "grant admin". Currently it's not clear in the UI who is owner and who is admin, they both are shown with a crown...

**Comment by N-Pex** [comment] 2018-04-05 15:08
Ok, crash will be fixed in 127.

**Comment by tiffrobo** [comment] 2018-04-10 17:48
@N-Pex okay! The iPad had no crashes during testing. 
So the new admins should be able to 'view the profile' and that is all?
If so, then we can close the ticket! 

Device: iPhone6, iPhone7, iPad
OS:
App version: 127

**Comment by cstiens** [comment] 2018-04-11 20:31
> So the new admins should be able to 'view the profile' and that is all?

Yes. But, we would want to cut out the shortcut/action sheet when an admin taps on a profile, since the only option for a contact is to 'view profile'. Instead, tapping on the contact, should open their profile. @N-Pex can you make that change?

**Comment by N-Pex** [comment] 2018-04-18 14:35
Yes, build 129.

**Comment by tiffrobo** [comment] 2018-04-20 15:09
No more shortcut. After becoming an 'Admin' if you tap on a profile, it opens the friends' profile view.

Device: iPhone 6, iPhone 7,  iPad
OS: 10.3.3, 11.2.2, 10.3.2
App version: build 129

**Closed** 2018-04-28 15:05 UTC
Labels: FOR REVIEW, bug
