### ISSUE TITLE
The lock with (!) on the top right of Chat

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-iOS#51] opened 2015-12-23 18:25 UTC
The lock with the exclamation mark seem to draw people there. Two new user I tested with clicked on the lock ;) just like i did the first time out of curiosity and the voice messages stopped working (I started not getting anything and they started getting encrypted codes instead. The lock doesn't respond after that.

Since Zom conversations are encrypted by default, can we remove that lock and place the contact's information there instead?

**Comment by n8fr8** [comment] 2016-04-11 19:44
duplicate of #83

**Closed by n8fr8** 2016-04-11 19:44 UTC
