### ISSUE TITLE
Invite link takes user to download page.

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-iOS#90] opened 2016-04-11 19:08 UTC
I shared a link in email to invite/add my friend from Zom onboarding page.
It took her to Zom website even when she has installed Zom on her iPhone.

**Comment by n8fr8** [comment] 2016-04-11 19:25
What app did she receive the link in?

**Comment by n8fr8** [comment] 2016-04-11 19:38
This is duplicate of  #91

**Closed by n8fr8** 2016-04-11 19:38 UTC
