### ISSUE TITLE
User should not be able to send a message until approved by the contact added

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#226] opened 2017-01-26 01:48 UTC
I believe this is a bug. I know we had this working, but in the last test flight version, I was able to send messages to contacts that I had just added before they approved me.

@N-Pex Can you look into this?

**Comment by chrisballinger** [comment] 2017-01-26 04:34
During our merge investigation we found that we need to better address this issue in general. Although it's generally not a good idea to send messages to contacts that you haven't added you back, in XMPP land it's technically possible and "valid" for someone to only be your contact in one direction. There are actually five(?) distinct states in XMPP:

1. Neither user is added to each other's server-side "roster". Technically you can still send messages (e.g. spam) this way but it's totally up to the server and client how to handle these.
2. "none" - friend added to your roster, but neither side is allowing subscription to presence events and PEP updates
3. "to" - you can see your buddy's presence, but you aren't allowing them to see yours
4. "from" - your buddy can see your presence, but you can't see theirs
5. "both" - what you'd actually expect for "approved" buddies

We had an issue reported upstream where contacts were being marked as "Pending Approval" even though you were receiving messages from them. The cause was that the subscription was "from"-only, which we didn't treat as approved.

To solve this issue we started allowing users to enter "Pending Approval" conversations because there's a chance that you can receive messages from someone that's not considered "Approved". Perhaps we can rethink the logic for what's considered "Pending Approval" to include the case where you've added someone to your roster (cases 2,3,4,5), and you've received >1 messages from them.

Since it's still technically valid to be able to send messages to people who haven't "approved" you, I might want to keep that ability to enter "Pending" conversations available upstream for better compliance to what's possible in generic XMPP clients. However, it's definitely confusing for an end user, should probably be avoided entirely in Zom.

**Comment by cstiens** [comment] 2017-01-26 16:33
@chrisballinger Could we use state 1 for both sides (neither is added to the roster) until the added contact is approved? Then both contacts would be (technically) added to the roster at the same time, and could then start chatting. We would still need to reveal in the UI which friends you've invited that are pending approval. But, could we say that technically aren't a part of your roster, and just display the IDs that you've sent an invite to in the UI? 

Food for thought. This could totally not work. But I wanted to throw it out there.

**Comment by n8fr8** [comment] 2017-01-26 19:24
The issue with this was that OTR handshake was being started before the other side is ready to start accepting them. This means some of the initial messages were dropped, and both sides got into a crazy OTR state during this initial "add friend" experience. This often ended up with a bunch of "OTR Error" messages being sent from the iOS to Android, which caused a brand new happy users to become quite less so.

So, I agree we should let people to try to start chatting ASAP, but we should also do a better job of hiding any OTR error messages that might occur due to that.

**Comment by cstiens** [comment] 2017-01-31 20:37
I've been testing this issue. When I click on a link sent via email, there were no issues with not receiving messages. Here's a run down of that scenario:

**Test 1**
I set up a burner account on iPhone
Sent a link via email for the Android Zom account (crwinfrey)
Tapped on the link from iPhone to add crwinfrey
Burner account wasn’t on my Android roster, since I had shared the link via email. So, there weren’t any problems with being able to send a message before I was approved.

I did have an issue when I manually added a friend's ID in the Add Friends view. Here's the run down:
**Test 4**
I added an iOS friend on Android, by entering their ID in the add friends view.
The contact I added showed up in my friends list, and I can tap on them to send a message. So, I did send a message.
There was a delay (1ish min) before the friend request showed up on iOS, but it did show with the option to approve.
Once I approved (on iOS), I tapped on the
conversation to open it, and I did not get the message that was sent from Android before I approved them.

@n8fr8 Have you found similar results in your testing?

**Comment by n8fr8** [comment] 2017-02-01 17:18
A little bit. Here is one "send before approved" fail state:

- I sent invite to iPhone user
- iPhone user added me, and then went left the app / went offline
- I received friend request on Android, and approved
- I approved, and then could send a message, but since they were offline AND we hadn't exchanged OTR ChatSecure Push tokens yet, I couldn't send her a push message
- My messages were not delivered

I think this could be solved on Android by basically always holding outbound messages until there is a valid OTR session, and the remote contact is online.

**Comment by n8fr8** [comment] 2017-02-01 17:19
I think this is also a subtle issue we need more time to work, and that if we can get a release out this week w/o it, I am okay with that.

**Comment by cstiens** [comment] 2017-02-01 17:20
Ok. Thank you Nathan!

**Comment by chrisballinger** [comment] 2017-02-01 17:48
> I think this could be solved on Android by basically always holding outbound messages until there is a valid OTR session, and the remote contact is online.

The `omemo` merge includes the message queue functionality that will do exactly that, including reconnecting your own account, and establishing a fresh OTR session. It will keep the messages around in the queue if any of that fails, marked with an error, allowing the user to manually resend the failed messages. 

Automatically resending is a more difficult problem due to issues with message ordering / history, deduplication, and unreliable support for delivery receipts.

**Closed** 2017-09-15 15:34 UTC
Labels: Fixed with OMEMO
